services:
  - type: web
    name: dog-disease-api
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -w 1 -k gthread --threads 1 -t 120 -b 0.0.0.0:$PORT
    envVars:
      - key: MODEL_PATH
        value: model.tflite
      - key: NUM_THREADS
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
