services:
  - type: web
    name: dog-disease-api
    env: python
    plan: starter         # free for testing: 'free'
    region: oregon        # pick close to users
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --listen=0.0.0.0:$PORT app:app
    envVars:
      - key: MODEL_PATH
        value: dog_disease_detector.h5
      - key: LAST_CONV_LAYER_NAME
        value: top_conv
    healthCheckPath: /health
    autoDeploy: true
    scaling:              # optional: keep 1 instance warm
      minInstances: 1
      maxInstances: 1
